"""Generate SYNTHETIC RLTech AC 8080 page fixtures.

These fixtures are NOT captured from a device. They are built from SDK source
so parser tests can run before real (sanitized) captures from stage 0 exist.
Replace or extend them with real samples once the AC is reachable.

Sources used (git_FTTR SDK):
- apps/private/webPage/Router/e8c_ml_new_utf8/boaroot/cgi-bin/ap_online_list.asp:22
  ``var AP_manage = '<% tcWebApi_JsonHook("XQuery_AP_List", ...) %>';``
- apps/private/webPage/Router/e8c_ml_new_utf8/boaroot/cgi-bin/ap_online_detail.asp:19-33
  ``var lan_pon_num``, ``var list_ap ='<% ...XQuery_AP_Info... %>'`` and
  ``let list_pon = '<% ...registerinfo... %>';``
- apps/public/boa-asp/src/asp/asp_handler.c:3188-3270 (XQuery_AP_List) and
  :3274-3330 (XQuery_AP_Info): ubus output is read into a 1024-byte buffer
  (AP info only), every space/tab is removed and newlines become one space.
- apps/public/boa-asp/src/asp/asp_handler.c:4686-4770 (registerinfo): same
  1024-byte buffer, tabs removed but spaces kept.
- apps/private/acap_db/acap_db_ap_list.c:7-12, :85-92 column order; and
  acap_db_common.c list_callback/single_info_callback: every column is emitted
  as a JSON string, SQL NULL becomes the literal string "NULL".
- source/lan_mgr/slaveMgr_v2/server/ubus/object/obj_slavemgr_ap.c:204-270:
  ``respCode`` is a u32 added before the DB JSON.
- apps/private/ap_server/ap_support.c:559-568: registerinfo ``data`` is a JSON
  *string* containing an escaped object; "1970-01-01 08:00:00" is the
  "never" sentinel for last_down_time/last_dying_gasptime.

Identities (MAC/SN/IP) are fake: locally administered MACs 02:00:5E:10:00:0x,
SN RLGM5E10000x and TEST-NET-1 addresses 192.0.2.x.

Run: python3 tests/fixtures/generate_synthetic.py
"""

from __future__ import annotations

import json
from pathlib import Path

HERE = Path(__file__).parent
BOA_AP_INFO_BUFFER = 1024

HEADER = (
    "<!-- SYNTHETIC fixture generated by tests/fixtures/generate_synthetic.py;"
    " NOT a device capture. Based on git_FTTR {source}. -->\n"
)


def ubus_pretty(value: object, indent: int = 0) -> str:
    """Approximate libubox blobmsg_format_json_indent output (tab indented)."""
    pad = "\t" * indent
    inner = "\t" * (indent + 1)
    if isinstance(value, dict):
        if not value:
            return "{ }"
        items = [
            f'{inner}{json.dumps(key)}: {ubus_pretty(item, indent + 1)}'
            for key, item in value.items()
        ]
        return "{\n" + ",\n".join(items) + "\n" + pad + "}"
    if isinstance(value, list):
        items = [f"{inner}{ubus_pretty(item, indent + 1)}" for item in value]
        return "[\n" + ",\n".join(items) + "\n" + pad + "]"
    return json.dumps(value)


def boa_strip_all_whitespace(text: str, *, limit: int | None = None) -> str:
    """Mimic XQuery_AP_List/XQuery_AP_Info post-processing."""
    if limit is not None:
        # fgets+snprintf into char[limit] keeps at most limit-1 bytes.
        text = text.encode("utf-8")[: limit - 1].decode("utf-8", "ignore")
    out = []
    for char in text:
        if char == "\n":
            out.append(" ")
        elif char in " \t\b":
            continue
        else:
            out.append(char)
    return "".join(out)


def boa_strip_tabs(text: str, *, limit: int | None = None) -> str:
    """Mimic registerinfo post-processing (spaces are kept)."""
    if limit is not None:
        text = text.encode("utf-8")[: limit - 1].decode("utf-8", "ignore")
    return "".join(
        " " if char == "\n" else "" if char in "\t\b" else char for char in text
    )


AP1 = {
    "Model": "RL820GW-AX3",
    "IP": "192.0.2.10",
    "Version": "V0.0.51",
    "Mac": "02005E100001",
    "Status": "1",
    "Profile": "Default",
    "ChannelG24": "9",
    "ChannelG5": "52",
    "Assoc": "3",
    "Alias": "820",
    "BssidG24": "02005E100004",
    "BssidG5": "02005E100005",
    "Uplink": "2",
    "UplinkPort": "6",
    "SN": "RLGM5E100001",
    "DevSN": "RL00000000001",
    "UpgradeFlag": "1",
    "ProfileIdx": "1",
    "OptTxPower": "2.15",
    "OptRxPower": "-18.42",
}

AP2 = {
    "Model": "FS8820A",
    "IP": "192.0.2.4",
    "Version": "V0.1.21",
    "Mac": "02005E100002",
    "Status": "1",
    "Profile": "Default",
    "ChannelG24": "3",
    "ChannelG5": "36",
    "Assoc": "2",
    "Alias": "",
    "BssidG24": "02005E100006",
    "BssidG5": "02005E100007",
    "Uplink": "2",
    "UplinkPort": "6",
    "SN": "RLGM5E100002",
    "DevSN": "RL00000000002",
    "UpgradeFlag": "1",
    "ProfileIdx": "1",
    # Column added by tb_add_new_column: old rows report SQL NULL as "NULL".
    "OptTxPower": "NULL",
    "OptRxPower": "",
}


def ap_info_row(list_row: dict[str, str], **overrides: str) -> dict[str, str]:
    """Build an XQuery_AP_Info data object in acap_db_ap_list.c:85-92 order."""
    row = {
        "Model": list_row["Model"],
        "IP": list_row["IP"],
        "Version": list_row["Version"],
        "Mac": list_row["Mac"],
        "Status": list_row["Status"],
        "Profile": list_row["Profile"],
        "ChannelG24": list_row["ChannelG24"],
        "ChannelG5": list_row["ChannelG5"],
        "Assoc": list_row["Assoc"],
        "Alias": list_row["Alias"],
        "SN": list_row["SN"],
        "Uplink": list_row["Uplink"],
        "UplinkPort": list_row["UplinkPort"],
        "Fingerprint": "5A0C1B2E-3F40-4D51-8E62-7F8091A2B3C4",
        "LastOfflineReason": "",
        "BssidG24": list_row["BssidG24"],
        "BssidG5": list_row["BssidG5"],
        "SysDuration": "86461",
        "RamSize": "536870912",
        "FlashSize": "268435456",
        "DevName": "FTTRSub_100001",
        "CPUUsage": "7",
        "CPUTemp": "63",
        "MEMUsage": "41",
        "FlashUsage": "86",
        "DevSN": list_row["DevSN"],
        "UpgradeFlag": list_row["UpgradeFlag"],
        "ProfileIdx": list_row["ProfileIdx"],
        "OptTxPower": list_row["OptTxPower"],
        "OptRxPower": list_row["OptRxPower"],
    }
    row.update(overrides)
    return row


PON_AP1 = {
    "pon_id": 2,
    "onu_id": 0,
    "pon_sn": "RLGM5E100001",
    "opt_temperature": " 48.20",
    "opt_current": " 11.02",
    "opt_voltage": "  3.28",
    "opt_tx_power": "  2.21",
    "opt_rx_power": "-18.37",
    "active": 1,
    "onu_status": "online",
    "ont_distance": 12,
    "opt_err_status": 0,
    "last_up_time": "2026-09-28 18:25:02",
    "last_down_time": "2026-09-28 18:24:10",
    "last_dying_gasptime": "1970-01-01 08:00:00",
    "last_down_cause": "Reboot",
    "dnopt_rx_power": "-19.86",
    "identify_vendor": "RLGM",
    "equipment_id": "RL820GW-AX3",
    "sn_address": "RLGM-5E100001",
    "hardware_version": "N/A",
    "software_version": "V0.0.51",
    "fireware_version": "N/A",
}


def list_page(rows: list[dict[str, str]]) -> str:
    reply = {
        "respCode": 0,
        "total": len(rows),
        "count": len(rows),
        "data": {"list": rows},
    }
    body = boa_strip_all_whitespace(ubus_pretty(reply) + "\n")
    return (
        HEADER.format(source="ap_online_list.asp:22 + asp_handler.c:3188")
        + "<HTML><BODY>\n<script language=\"JavaScript\" type=\"text/javascript\">\n"
        + f"        var AP_manage = '{body}';\n"
        + "        var ret = JSON.parse(AP_manage);\n"
        + "</script></BODY></HTML>\n"
    )


def detail_page(
    info: dict[str, str] | None,
    pon_reply: dict[str, object] | None,
    *,
    lan_pon_num: str = "2",
    source: str,
) -> str:
    if info is None:
        list_ap = ""
    else:
        list_ap = boa_strip_all_whitespace(
            ubus_pretty({"respCode": 0, "data": info}) + "\n",
            limit=BOA_AP_INFO_BUFFER,
        )
    if pon_reply is None:
        list_pon = ""
    else:
        list_pon = boa_strip_tabs(
            ubus_pretty(pon_reply) + "\n", limit=BOA_AP_INFO_BUFFER
        )
    return (
        HEADER.format(source=source)
        + "<HTML><HEAD>\n<SCRIPT>\n"
        + f"var lan_pon_num = '{lan_pon_num}';\n"
        + f"var list_ap ='{list_ap}'\n"
        + "var ap_list_info = JSON.parse(list_ap)\n"
        + f"let list_pon = '{list_pon}';\n"
        + "let modifiedStr = list_pon.replace(/\"({[^{}]+})\"/g, '$1');\n"
        + "</SCRIPT></HEAD><BODY></BODY></HTML>\n"
    )


def pon_string_reply(data: dict[str, object]) -> dict[str, object]:
    # registerinfo "data" is a JSON string holding a serialized object. The
    # inner object comes from json-c, which escapes "/" as "\\/" (see the
    # "N\\\\\\/A" test vector in ap_support.c:566); libubox does not.
    inner = json.dumps(data, separators=(", ", ": ")).replace("/", "\\/")
    return {"result": 0, "data": inner}


def main() -> None:
    detail_src = "ap_online_detail.asp:19-33 + asp_handler.c:3274,4686"
    files = {
        "synthetic_ap_online_list.html": list_page([AP1, AP2]),
        # Full detail: list_ap + list_pon with data as an escaped JSON string.
        "synthetic_ap_online_detail_full.html": detail_page(
            ap_info_row(AP1, LastOfflineReason="Reboot"),
            pon_string_reply(PON_AP1),
            source=detail_src,
        ),
        # PON lookup failed (result 9 per ap_online_detail.asp:288,339) so the
        # page falls back to list_ap OptTx/RxPower; last_down_time is absent.
        "synthetic_ap_online_detail_no_pon.html": detail_page(
            ap_info_row(
                AP2,
                DevName="FTTRSub_100002",
                SysDuration="3605",
                OptTxPower="1.98",
                OptRxPower="-20.05",
                LastOfflineReason="Offline",
            ),
            {"result": 9},
            source=detail_src,
        ),
        # registerinfo produced no output (ubus object missing): empty string.
        "synthetic_ap_online_detail_empty_pon.html": detail_page(
            ap_info_row(AP1),
            None,
            source=detail_src,
        ),
        # Long field values push XQuery_AP_Info past the 1024-byte boa buffer
        # (asp_handler.c:3276), so list_ap JSON is cut mid-object.
        "synthetic_ap_online_detail_truncated.html": detail_page(
            ap_info_row(
                AP1,
                Alias="Living_Room_Upstairs_Corridor_Ceiling_AP_Primary_Unit_01"
                "_Second_Floor_East_Wing",
                DevName="FTTRSub_100001_with_a_really_long_hostname_value_x"
                "_that_keeps_going_for_padding_purposes_only",
                LastOfflineReason="LinkDown_OpticalSignalLost_Timeout_Retry"
                "_After_Watchdog_Expired_On_Uplink_Port_Six_Of_Controller",
                Profile="Enterprise_Deployment_Profile_Group_A_Default",
            ),
            pon_string_reply(PON_AP1),
            source=detail_src,
        ),
    }
    for name, text in files.items():
        (HERE / name).write_text(text, encoding="utf-8")
        print(f"wrote {name} ({len(text)} bytes)")


if __name__ == "__main__":
    main()
